name: Autograding

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clone hidden tests
        env:
          TOKEN: ${{ secrets.HIDDEN_TESTS_TOKEN }}
        run: |
          git clone https://$TOKEN@github.com/MachineLearningForAll/hidden_tests.git temp_hidden
          cp -r temp_hidden/hidden_tests ./hidden_tests


      - name: Run visible tests
        run: PYTHONPATH=. pytest tests/

      - name: Run hidden tests
        run: PYTHONPATH=. pytest -q hidden_tests/ > hidden_test_result.txt
        continue-on-error: true

      - name: Check hidden test result
        run: |
         if grep -q "F" hidden_test_result.txt; then
          echo "Some hidden tests failed. Please check your implementation.";
          exit 1
         else
          echo "All hidden tests passed!";
         fi

